### ISSUE TITLE
.fbx Re-Exporting Characters and Animations to Unity

### ISSUE THREAD

**Issue by mertakbal** [soupday/cc_blender_tools#144]
**Following steps:**
- import character from CC
- edit with rigify
- export .fbx to unity
- re-import .fbx to blender
- edit in blender
- re-export to unity as .fbx

**throws following error:**
Traceback (most recent call last):
  File "/home/mrt/.config/blender/3.5/scripts/addons/cc_blender_tools-main/exporter.py", line 2145, in execute
    export_to_unity(self, chr_cache, self.include_anim, self.filepath, self.include_selected)
  File "/home/mrt/.config/blender/3.5/scripts/addons/cc_blender_tools-main/exporter.py", line 1807, in export_to_unity
    set_T_pose(arm, json_data[name]["Object"][name])
TypeError: 'NoneType' object is not subscriptable

**Comment by soupday** [comment]
Why are you re-importing the export to Unity back into Blender? That export is meant for Unity only.

**Comment by soupday** [comment]
On the other hand, it might be useful to make that work.

**Comment by soupday** [comment]
In fact just tried this and it worked.

So does the character you originally imported into Blender have a .json file? and is it exported to unity with the rest of the character? (The error would suggest that it is missing)
