### ISSUE TITLE
Blender 4.0 beta armature layer compatability issue (w/ temporarly solution)

### ISSUE THREAD

**Issue by evokra** [soupday/cc_blender_tools#188]
Curret 1.6.0.4 version of addon is unusable in blender 4.0 beta when it comes to armature generation (i.e. import character, quick rigify characer). 

When importing character:
  File "C:\Users\USERNAME\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\cc_blender_tools-1_6_0_4\bones.py", line 573, in store_armature_settings
    layers.append(rig.data.layers[i])
AttributeError: 'Armature' object **has no attribute 'layers'**

When attempting to rigify character:
 File "C:\Users\USERNAME\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\cc_blender_tools-1_6_0_4\bones.py", line 573, in store_armature_settings
    layers.append(rig.data.layers[i])
AttributeError: 'Armature' object **has no attribute 'layers'**

I believe this is due to the update of armature layer feature in blender 4.0, as shown in the screenshots below.

3.6 layer UI:
![image](https://github.com/soupday/cc_blender_tools/assets/96784532/89131083-9684-4554-b445-a24734960ecd)
4.0 beta layer UI:
![image](https://github.com/soupday/cc_blender_tools/assets/96784532/7b55498b-e6c7-4c87-85fe-e29fe05f42a5)

Would appreciate if this inconvenience can be addressed, thanks.

**Comment by evokra** [comment]
Temporarly solution is to import/rigify the charater in 3.6 and open it in 4.0 beta.

**Comment by priceperrott** [comment]
I've encountered a similar issue which may be related to this in trying to import a character into Blender v4 with the following error messages received. I have raised as a support ticket.

The character and motion uploads do appear in Blender, but when I try to use the Rigimap add-on (I'm new to this so was trying it for the first time yesterday), it is telling me there is no Rigify armiture available.

I'm assuming it's due to this importer failing.  if anyone can spot a different problem, I'd appreciate pointers.

Thanks.

--

bpy.ops.cc3.importer(filepath="/Users/USERNAME/Documents/Blender add-ins/ActorCore downloads/Actors/party-f-0001/party-f-0001.fbx", param="IMPORT_QUALITY")
Python: Traceback (most recent call last):
  File "/Users/USERNAME/Library/Application Support/Blender/4.0/scripts/addons/cc_blender_tools-1_6_0_4/importer.py", line 1059, in modal
    self.run_finish(context)
  File "/Users/USERNAME/Library/Application Support/Blender/4.0/scripts/addons/cc_blender_tools-1_6_0_4/importer.py", line 1019, in run_finish
    bpy.ops.cc3.rigifier(param="ALL")
  File "/Applications/Blender.app/Contents/Resources/4.0/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/Users/USERNAME/Library/Application Support/Blender/4.0/scripts/addons/cc_blender_tools-1_6_0_4/rigging.py", line 3645, in execute
    self.generate_meta_rig(chr_cache)
  File "/Users/USERNAME/Library/Application Support/Blender/4.0/scripts/addons/cc_blender_tools-1_6_0_4/rigging.py", line 3485, in generate_meta_rig
    self.add_meta_rig(chr_cache)
  File "/Users/USERNAME/Library/Application Support/Blender/4.0/scripts/addons/cc_blender_tools-1_6_0_4/rigging.py", line 3445, in add_meta_rig
    match_meta_rig(chr_cache, self.cc3_rig, self.meta_rig, self.rigify_data)
  File "/Users/USERNAME/Library/Application Support/Blender/4.0/scripts/addons/cc_blender_tools-1_6_0_4/rigging.py", line 1119, in match_meta_rig
    hide_face_bones(meta_rig)
  File "/Users/USERNAME/Library/Application Support/Blender/4.0/scripts/addons/cc_blender_tools-1_6_0_4/rigging.py", line 1166, in hide_face_bones
    bone.layers[0] = False
AttributeError: 'EditBone' object has no attribute 'layers'
Location: /Applications/Blender.app/Contents/Resources/4.0/scripts/modules/bpy/ops.py:109
