### ISSUE TITLE
Export Replace AttributeError: Calling operator "bpy.ops.export_scene.obj" error, could not be found

### ISSUE THREAD

**Issue by pishah** [soupday/cc_blender_tools#199]
Python: Traceback (most recent call last):
  File "C:\Users\incen\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\cc_blender_tools-2_0_0\exporter.py", line 2235, in execute
    export_as_replace_mesh(self.filepath)
  File "C:\Users\incen\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\cc_blender_tools-2_0_0\exporter.py", line 2123, in export_as_replace_mesh
    bpy.ops.export_scene.obj(filepath=file_path,
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
AttributeError: Calling operator "bpy.ops.export_scene.obj" error, could not be found

**Comment by pishah** [comment]
For more context, using Blender 4.0.2. When searching Google I found an article that said bpy.ops.export_scene.obj no longer exists and to use bpy.ops.wm.obj_export(). I tried to replace the code in the PY file but I couldn't get it to work. I wish I knew more about it.

**Comment by Hazetheai** [comment]
Old issue, but in case anyone else ends up here:
The function signature is different for "bpy.ops.wm.obj_export()". The full line should be: 
`bpy.ops.wm.obj_export(filepath=fn + ".obj", export_selected_objects=True)`

Tested using the above edit in the template script `batch_export.py` version in 4.3.2

**Comment by soupday** [comment]
That was fixed 17 months ago in version 2.0.3. What version are you using?

In a version that old, there's a lot more than that won't work in Blender 4.3.

**Comment by Hazetheai** [comment]
Oops, I ended up here, thinking I was in the Blender repo, because of a similar issue to OP, but just using regular Blender - not cc_blender_tools. Sorry for the confusion!
