### ISSUE TITLE
Can't install the pack

### ISSUE THREAD

**Issue by Adlerannet** [soupday/cc_blender_tools#219]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\Anna\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\cc_blender_tools-main\__init__.py", line 59, in <module>
    from . import addon_updater_ops
  File "C:\Users\Anna\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\cc_blender_tools-main\addon_updater_ops.py", line 28, in <module>
    from bpy.app.handlers import persistent
  File "shibokensupport/signature/loader.py", line 61, in feature_imported
  File "shibokensupport/feature.py", line 135, in feature_imported
AttributeError: 'bpy.app.handlers' object has no attribute '__name__'

**Comment by ygypt** [comment]
I am getting the same error. It is a fresh install of Blender 4.1 (never used before) and while trying to add the zip it gives me this error
