### ISSUE TITLE
v2.0.7 issue when attempting to import with Rigify

### ISSUE THREAD

**Issue by 0xCarnival** [soupday/cc_blender_tools#228]
This is the error that I get:

Python: Traceback (most recent call last):
  File "/Users/x/Library/Application Support/Blender/4.1/scripts/addons/cc_blender_tools-2_0_7/importer.py", line 1258, in modal
    self.run_finish(context)
  File "/Users/x/Library/Application Support/Blender/4.1/scripts/addons/cc_blender_tools-2_0_7/importer.py", line 1157, in run_finish
    for chr_cache in self.imported_characters:
TypeError: 'CC3CharacterCache' object is not iterable

**Comment by gpotte** [comment]
I'm having the same issue on a model that my coworkers have no issue importing and rigging

**Comment by soupday** [comment]
What type of character is it? Standard CC3+, Gamebase, ActorCore, AccuRig, Humanoid? And is there a .json file with the character?

**Comment by soupday** [comment]
I think there's a case where if there's no json file with the character it won't recognise a reallusion character, even if it's valid.

**Comment by gpotte** [comment]
I'm using a rig from accurig and the export has no JSON file attached to it.
But i'm using the same file and the same version of the plugin has my coworker that doesnt come across this issue tho.

**Comment by soupday** [comment]
Different version of the add-on maybe? Or your coworker has the textures and you don't?
