### ISSUE TITLE
Blender console flooding with..

### ISSUE THREAD

**Issue by Gamerage** [soupday/cc_blender_tools#255]
TypeError: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Win10\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\cc_blender_tools-main\panels.py", line 2339, in draw
    motion_set_ui(layout, chr_cache, show_nla=True)
  File "C:\Users\Win10\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\cc_blender_tools-main\panels.py", line 2231, in motion_set_ui
    if "rl_set_generation" in rig:

I haven't imported anything from CC4 - I just open a scene with a rigged character that I was working on and noticed the above over and over again in the console? can it be fixed?

**Comment by Gamerage** [comment]
Or is it even a issue?

**Comment by soupday** [comment]
It not a serious problem, just annoying.
