### ISSUE TITLE
ValueError: bpy_struct: item.attr = val: sequences of dimension 0 should contain 2 items, not 0

### ISSUE THREAD

**Issue by truongvanvu0411** [soupday/cc_blender_tools#77]
I have import fbx from CC3 to Blender 3.1 issue as bellow, how can i fix that?

Python: Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\cc3_blender_tools-1_3_2\importer.py", line 732, in modal
    self.run_import(context)
  File "C:\Users\Acer\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\cc3_blender_tools-1_3_2\importer.py", line 646, in run_import
    self.import_character(warn)
  File "C:\Users\Acer\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\cc3_blender_tools-1_3_2\importer.py", line 532, in import_character
    bpy.ops.import_scene.fbx(filepath=self.filepath, directory=dir, use_anim=import_anim)
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\addons\io_scene_fbx\__init__.py", line 220, in execute
    return import_fbx.load(self, context, filepath=self.filepath, **keywords)
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\addons\io_scene_fbx\import_fbx.py", line 2603, in load
    _(); del _
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\addons\io_scene_fbx\import_fbx.py", line 2602, in _
    fbx_item[1] = blen_read_geom(fbx_tmpl, fbx_obj, settings)
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\addons\io_scene_fbx\import_fbx.py", line 1299, in blen_read_geom
    blen_read_geom_layer_uv(fbx_obj, mesh)
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\addons\io_scene_fbx\import_fbx.py", line 1064, in blen_read_geom_layer_uv
    blen_read_geom_array_mapped_polyloop(
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\addons\io_scene_fbx\import_fbx.py", line 987, in blen_read_geom_array_mapped_polyloop
    blen_read_geom_array_setattr(blen_read_geom_array_gen_indextodirect(fbx_layer_index, stride),
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\addons\io_scene_fbx\import_fbx.py", line 843, in blen_read_geom_array_setattr
    _process(blen_data, blen_attr, fbx_data, xform, item_size, blen_idx, fbx_idx)
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\addons\io_scene_fbx\import_fbx.py", line 838, in _process
    setattr(blen_data[blen_idx], blen_attr, fbx_data[fbx_idx:fbx_idx + item_size])
ValueError: bpy_struct: item.attr = val: sequences of dimension 0 should contain 2 items, not 0

location: C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\bpy\ops.py:132

location: <unknown location>:-1

**Comment by soupday** [comment]
Seen this error lots of times,

You wouldn't by any chance, be trying to import a character wearing the "Biker Vest"?

It has broken UV maps and crashes Blender. There's no way to fix inside Blender. 

There's a version of that vest in the "DH Sample" character (Content Tab: Scene Project Template > Project > DH Sample) that does work with Blender

**Comment by truongvanvu0411** [comment]
I got this. Thank you💛💛
